/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views.panels;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import ni.uni.edu.programacion.Controllers.PnlVehicleController;

/**
 *
 * @author FAMILIASOZAORTIZ
 */
public class PnlTableVehicle extends javax.swing.JPanel {
    private PnlVehicleController pnlVehicleController;

    
    /**
     * Creates new form PnlTable
     */
    public PnlTableVehicle() {
        initComponents();
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JPanel getjPanel1() {
        return pnlSearch;
    }

    public JPanel getPnlContent() {
        return pnlContent;
    }

    public JScrollPane getScrollContentTable() {
        return scrollContentTable;
    }

    public JTable getTblTableVehicle() {
        return tblTableVehicle;
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSearch = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        pnlContent = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollContentTable = new javax.swing.JScrollPane();
        tblTableVehicle = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTextField1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 204, 153));
        jTextField1.setText("Titulo");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        pnlSearch.add(jTextField1);

        add(pnlSearch, java.awt.BorderLayout.PAGE_START);

        pnlContent.setLayout(new java.awt.BorderLayout());
        pnlContent.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        tblTableVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Stock numer", "Year", "Make", "Model", "Style", "VIN", "Exterior color", "Interior color", "Miles", "Price", "Transmission", "Engine", "Image", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTableVehicle.setToolTipText("");
        scrollContentTable.setViewportView(tblTableVehicle);

        pnlContent.add(scrollContentTable, java.awt.BorderLayout.CENTER);

        add(pnlContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JScrollPane scrollContentTable;
    private javax.swing.JTable tblTableVehicle;
    // End of variables declaration//GEN-END:variables
}
