/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.calculator;

import ni.edu.uni.programacion.panel.views.PnlCalculator;
import java.awt.BorderLayout;
import ni.edu.uni.programacion.panel.views.PnlMoneda;
import ni.edu.uni.programacion.panel.views.PnlTemperture;
/**
 *
 * @author LENOVO 17
 */
public class MyApp extends javax.swing.JFrame {
    
    private PnlCalculator pnlCalculator;
    private PnlTemperture pnltemp;
    private PnlMoneda pnlmoneda;
    /**
     * Creates new form MyApp
     */
    public MyApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlLeftButtons = new javax.swing.JPanel();
        BtnCalculadora = new javax.swing.JButton();
        BtnTemp = new javax.swing.JButton();
        BtnCoin = new javax.swing.JButton();
        PnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MathApp");
        setAutoRequestFocus(false);

        PnlLeftButtons.setBackground(new java.awt.Color(51, 255, 102));
        PnlLeftButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        PnlLeftButtons.setLayout(new java.awt.GridLayout(3, 1));

        BtnCalculadora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnCalculadora.setText("Calculadora");
        BtnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalculadoraActionPerformed(evt);
            }
        });
        PnlLeftButtons.add(BtnCalculadora);

        BtnTemp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnTemp.setText("Temperatura");
        BtnTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTempActionPerformed(evt);
            }
        });
        PnlLeftButtons.add(BtnTemp);

        BtnCoin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnCoin.setText("Moneda");
        BtnCoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCoinActionPerformed(evt);
            }
        });
        PnlLeftButtons.add(BtnCoin);

        getContentPane().add(PnlLeftButtons, java.awt.BorderLayout.LINE_START);

        PnlContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(PnlContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(600, 350));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalculadoraActionPerformed
      if(pnlCalculator==null){
          pnlCalculator=new PnlCalculator();
      }
      if(PnlContent.getComponentCount() > 0){
        PnlContent.remove(0);
    }
      
      PnlContent.add(pnlCalculator, BorderLayout.CENTER);
      this.validate();
      
    }//GEN-LAST:event_BtnCalculadoraActionPerformed

    private void BtnTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTempActionPerformed
        if(pnltemp==null){
            pnltemp=new PnlTemperture();
        }
        if(PnlContent.getComponentCount()>0){
            PnlContent.remove(0);
        }
        PnlContent.add(pnltemp,BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_BtnTempActionPerformed

    private void BtnCoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCoinActionPerformed
        if(pnlmoneda==null){
            pnlmoneda=new PnlMoneda();
        }
        if(PnlContent.getComponentCount()>0){
            PnlContent.remove(0);
        }
        PnlContent.add(pnlmoneda,BorderLayout.CENTER);
        this.validate();
    }//GEN-LAST:event_BtnCoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalculadora;
    private javax.swing.JButton BtnCoin;
    private javax.swing.JButton BtnTemp;
    private javax.swing.JPanel PnlContent;
    private javax.swing.JPanel PnlLeftButtons;
    // End of variables declaration//GEN-END:variables
}
