/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.panel.views;

/**
 *
 * @author LENOVO 17
 */
public class PnlCalculator extends javax.swing.JPanel {

    /**
     * Creates new form PnlCalculator
     */
    public PnlCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtNumber1 = new javax.swing.JTextField();
        JLabel2 = new javax.swing.JLabel();
        TxtNumber2 = new javax.swing.JTextField();
        JLabel3 = new javax.swing.JLabel();
        TxtResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnSuma = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnResi = new javax.swing.JButton();
        BtnMult = new javax.swing.JButton();
        BtnNew = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Numero 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(TxtNumber1, gridBagConstraints);

        JLabel2.setText("Numero 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(JLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(TxtNumber2, gridBagConstraints);

        JLabel3.setText("Resultado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(JLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel1.add(TxtResult, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        BtnSuma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnSuma.setText("Suma");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSuma);

        BtnResta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnResta.setText("Resta");
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnResta);

        BtnResi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnResi.setText("Division");
        BtnResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResiActionPerformed(evt);
            }
        });
        jPanel2.add(BtnResi);

        BtnMult.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnMult.setText("Multiplicacion");
        BtnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultActionPerformed(evt);
            }
        });
        jPanel2.add(BtnMult);

        BtnNew.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnNew.setText("Nuevo");
        BtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewActionPerformed(evt);
            }
        });
        jPanel2.add(BtnNew);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        double n1,n2;
        n1=Double.parseDouble(TxtNumber1.getText());
        n2=Double.parseDouble(TxtNumber2.getText());
        
        TxtResult.setText(String.valueOf(suma(n1,n2)));
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewActionPerformed
        TxtNumber1.setText(null);
        TxtNumber2.setText(null);
        TxtResult.setText(null);
    }//GEN-LAST:event_BtnNewActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        double n1,n2;
        n1=Double.parseDouble(TxtNumber1.getText());
        n2=Double.parseDouble(TxtNumber2.getText());
        
        TxtResult.setText(String.valueOf(resta(n1,n2)));
    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResiActionPerformed
        double n1,n2;
        n1=Double.parseDouble(TxtNumber1.getText());
        n2=Double.parseDouble(TxtNumber2.getText());
        
        TxtResult.setText(String.valueOf(divi(n1,n2)));
    }//GEN-LAST:event_BtnResiActionPerformed

    private void BtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultActionPerformed
        double n1,n2;
        n1=Double.parseDouble(TxtNumber1.getText());
        n2=Double.parseDouble(TxtNumber2.getText());
        
        TxtResult.setText(String.valueOf(mult(n1,n2)));
    }//GEN-LAST:event_BtnMultActionPerformed

    private double suma(double a,double b){
        return a+b;
    }
    private double resta(double a,double b){
        return a-b;
    }
    private double divi(double a, double b){
        return a/b;
    }
    private double mult(double a, double b){
        return a*b;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMult;
    private javax.swing.JButton BtnNew;
    private javax.swing.JButton BtnResi;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel JLabel3;
    private javax.swing.JTextField TxtNumber1;
    private javax.swing.JTextField TxtNumber2;
    private javax.swing.JTextField TxtResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
