/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.panel.views;

import java.text.DecimalFormat;

/**
 *
 * @author LENOVO 17
 */
public class PnlMoneda extends javax.swing.JPanel {

    /**
     * Creates new form PnlMoneda
     */
    public PnlMoneda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtCoin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnDolar = new javax.swing.JButton();
        BtnEuro = new javax.swing.JButton();
        BtnNuev = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cordobas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(TxtResultado, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Resultado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(TxtCoin, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 51, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        BtnDolar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnDolar.setText("Dolar");
        BtnDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDolarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnDolar);

        BtnEuro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnEuro.setText("Euro");
        BtnEuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEuroActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEuro);

        BtnNuev.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnNuev.setText("Nuevo");
        BtnNuev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevActionPerformed(evt);
            }
        });
        jPanel2.add(BtnNuev);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevActionPerformed
        TxtResultado.setText(null);
        TxtCoin.setText(null);
    }//GEN-LAST:event_BtnNuevActionPerformed

    private void BtnDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDolarActionPerformed
        double n1;
        n1=Double.parseDouble(TxtCoin.getText());
        TxtResultado.setText(String.valueOf(dolar(n1)));
    }//GEN-LAST:event_BtnDolarActionPerformed

    private void BtnEuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEuroActionPerformed
        double n1;
        n1=Double.parseDouble(TxtCoin.getText());
        TxtResultado.setText(String.valueOf(euro(n1)));
    }//GEN-LAST:event_BtnEuroActionPerformed

    private String dolar(double n1){
        double result = n1;
        
         DecimalFormat df = new DecimalFormat("#.00");
        
        result = result/ 35;
        return df.format(result);
    }

    private String euro(double n1){
        double result = n1;
       
        DecimalFormat df = new DecimalFormat("#.00");
    
        result = result/ 42;
        return  df.format(result);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDolar;
    private javax.swing.JButton BtnEuro;
    private javax.swing.JButton BtnNuev;
    private javax.swing.JTextField TxtCoin;
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
