/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.panel.views;

/**
 *
 * @author LENOVO 17
 */
public class PnlTemperture extends javax.swing.JPanel {

    /**
     * Creates new form PnlTemperture
     */
    public PnlTemperture() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtGrad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnFar = new javax.swing.JButton();
        BtnCel = new javax.swing.JButton();
        BtnNue = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Grados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(TxtGrad, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Resultado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
        jPanel1.add(TxtResult, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        BtnFar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnFar.setText("° F");
        BtnFar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnFar);

        BtnCel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnCel.setText("° C");
        BtnCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCelActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCel);

        BtnNue.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BtnNue.setText("Nuevo");
        BtnNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNueActionPerformed(evt);
            }
        });
        jPanel2.add(BtnNue);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNueActionPerformed
        TxtGrad.setText(null);
        TxtResult.setText(null);
    }//GEN-LAST:event_BtnNueActionPerformed

    private void BtnCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCelActionPerformed
        double n1;
        
        n1=Double.parseDouble(TxtGrad.getText());
        TxtResult.setText(String.valueOf(Cel(n1)));
    }//GEN-LAST:event_BtnCelActionPerformed

    private void BtnFarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFarActionPerformed
        double n1;
        n1=Double.parseDouble(TxtGrad.getText());
        TxtResult.setText(String.valueOf(Farenheit(n1)));
    }//GEN-LAST:event_BtnFarActionPerformed

    private double Farenheit(double n1){
        return (n1*1.8)+32;
    }
    private double Cel(double n1){
        return (n1-32)/1.8;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCel;
    private javax.swing.JButton BtnFar;
    private javax.swing.JButton BtnNue;
    private javax.swing.JTextField TxtGrad;
    private javax.swing.JTextField TxtResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
