/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views.panels;
import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static ni.uni.edu.programacion.views.panels.PnlMoneda.validar;
/**
 *
 * @author Héctor Fuentes
 */
public class PnlTemperature extends javax.swing.JPanel {

    /**
     * Creates new form PnlTemperature
     */
    public PnlTemperature() {
        initComponents();
    }
 public JButton getBntCalcC() {
        return bntCalcC;
    }

    public void setBntCalcC(JButton bntCalc) {
        this.bntCalcC = bntCalcC;
    }
    public JButton getBntCalc() {
        return bntCalc;
    }

    public void setBntCalc(JButton bntCalc) {
        this.bntCalc = bntCalc;
    }

    public JButton getBntNew() {
        return bntNew;
    }

    public void setBntNew(JButton bntNew) {
        this.bntNew = bntNew;
    }

    public JTextField getTxtC() {
        return txtC;
    }

    public void setTxtC(JTextField txtC) {
        this.txtC = txtC;
    }

    public JTextField getTxtF() {
        return txtF;
    }

    public void setTxtF(JTextField txtF) {
        this.txtF = txtF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntCalcC = new javax.swing.JButton();
        bntCalc = new javax.swing.JButton();
        bntNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bntCalcC.setText("Calcular Cº-Fº");
        bntCalcC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcCActionPerformed(evt);
            }
        });
        jPanel1.add(bntCalcC);

        bntCalc.setText("Calcular Fº-Cº");
        bntCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntCalcMouseClicked(evt);
            }
        });
        jPanel1.add(bntCalc);

        bntNew.setText("Nuevo");
        jPanel1.add(bntNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Fº");

        txtF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtF.setText("          ");
        txtF.setMinimumSize(new java.awt.Dimension(50, 20));
        txtF.setName(""); // NOI18N
        txtF.setSelectionEnd(8);
        txtF.setSelectionStart(8);
        txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFActionPerformed(evt);
            }
        });

        jLabel2.setText("Cº");

        txtC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtC.setText("        ");
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(80, 80, 80))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_txtFActionPerformed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
       
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed
public static boolean validar(String datos){
    return datos.matches("[0-9]");
}
    private void bntCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCalcMouseClicked
        // TODO add your handling code here:
        if(!validar(txtF.getText().trim())){
           JOptionPane.showMessageDialog(bntNew,"los datos no son correctos");
       }
      DecimalFormat f = new DecimalFormat("0.00");
             double num1,total;
             num1 = Double.parseDouble(getTxtF().getText());
            total=(num1-32)/(1.8);
            getTxtC().setText(String.valueOf(f.format(total)));
           
           
    }//GEN-LAST:event_bntCalcMouseClicked

    private void bntCalcCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcCActionPerformed
        if(!validar(txtC.getText().trim())){
           JOptionPane.showMessageDialog(bntNew,"los datos son incorrectos");
       }
        DecimalFormat f = new DecimalFormat("0.00");
             double num1,total;
             num1 = Double.parseDouble(getTxtC().getText());          
            total=((num1*(1.8))+32);
            getTxtF().setText(String.valueOf(f.format(total)));
           
           
    }//GEN-LAST:event_bntCalcCActionPerformed
private void Components(){
     java.awt.GridBagConstraints gridBagConstraints;
     jPanel1 = new javax.swing.JPanel();
        bntCalc = new javax.swing.JButton();
        bntNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtF = new javax.swing.JTextField();
        
        
        
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        bntCalc.setText("Calcular");
        jPanel1.add(bntCalc);

        bntNew.setText("Nuevo");
        jPanel1.add(bntNew);
        
        
        
        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Numero 1:");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());
 txtC.addActionListener(this::txtCActionPerformed);
 txtC.addActionListener(this::txtCActionPerformed);
 gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtF, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtC, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Resultado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtC, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalc;
    private javax.swing.JButton bntCalcC;
    private javax.swing.JButton bntNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtF;
    // End of variables declaration//GEN-END:variables
}
