/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.uni.edu.programacion.views;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.Element;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import ni.uni.edu.programacion.Controllers.FileConsequence;
import ni.uni.edu.programacion.views.panels.PnlEditor;
import say.swing.JFontChooser;

/**
 *
 * @author Sistemas-05
 */
public class FrmEditor extends javax.swing.JFrame {
    private int countTab;
    private FileConsequence fileConsequence;
    private JFontChooser fontChooser;
    /**
     * Creates new form FrmEditor
     */
    public FrmEditor() {
        countTab = 1;
        initComponents();
        PnlEditor pnlEditor = new PnlEditor();
        tbpContent.addTab("Editor "+ countTab++, pnlEditor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCloseTab = new javax.swing.JButton();
        tglBold = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        tbpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mniNew = new javax.swing.JMenuItem();
        mniOpen = new javax.swing.JMenuItem();
        mniSaveAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniTextFormat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor");

        jToolBar1.setRollover(true);

        btnCloseTab.setText("X");
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCloseTab);

        tglBold.setText("Bold");
        tglBold.setFocusable(false);
        tglBold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBoldActionPerformed(evt);
            }
        });
        jToolBar1.add(tglBold);

        jToggleButton2.setText("Justify");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(tbpContent, java.awt.BorderLayout.CENTER);

        mnFile.setText("File");

        mniNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mniNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/New2.png"))); // NOI18N
        mniNew.setText("New");
        mniNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewActionPerformed(evt);
            }
        });
        mnFile.add(mniNew);

        mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mniOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnFile.add(mniOpen);

        mniSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mniSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save as.png"))); // NOI18N
        mniSaveAs.setText("Save As");
        mniSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveAsActionPerformed(evt);
            }
        });
        mnFile.add(mniSaveAs);
        mnFile.add(jSeparator1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnFile.add(mniExit);

        jMenuBar1.add(mnFile);

        jMenu2.setText("Edit");

        mniTextFormat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mniTextFormat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit icon.png"))); // NOI18N
        mniTextFormat.setText("Text Format");
        mniTextFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTextFormatActionPerformed(evt);
            }
        });
        jMenu2.add(mniTextFormat);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewActionPerformed
        PnlEditor pnlEditor = new PnlEditor();
        tbpContent.addTab("Editor " + countTab++, pnlEditor);
    }//GEN-LAST:event_mniNewActionPerformed

    private void btnCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseTabActionPerformed
        if(tbpContent.getComponentCount() <= 0){
            return;
        }
        
        int option = JOptionPane.showConfirmDialog(null,
                "Are you sure to delete this tab?", 
                "Confirm Dialog", 
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(option == 1){
            return;
        }
        
        int index = tbpContent.getSelectedIndex();
        tbpContent.remove(index);
    }//GEN-LAST:event_btnCloseTabActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        JFileChooser fileChooser =  new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "txt Files", "txt");
        
        fileChooser.setFileFilter(filter); //Colocar el filtro txt
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            openFile(fileChooser);
            JOptionPane.showMessageDialog(null, "Open File: "+ fileChooser.getSelectedFile().getName());
        } 
    }//GEN-LAST:event_mniOpenActionPerformed

    private void openFile(JFileChooser fileChooser) {
        File file = fileChooser.getSelectedFile();    
        
        fileConsequence = new FileConsequence(file); //Creacion de los Flujos
        
        PnlEditor pnlEditor = new PnlEditor();
        tbpContent.addTab(file.getName(),pnlEditor);
        
        try {
            pnlEditor.getTxtpEditor().setText(fileConsequence.read(file));
        } catch (IOException ex) {
            Logger.getLogger(FrmEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mniSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveAsActionPerformed
         JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "txt Files", "txt");
        int index = tbpContent.getSelectedIndex();
        
        filechooser.setFileFilter(filter); //Coloca el filtro solo txt
        
        int option = filechooser.showSaveDialog(this);
        
        if (option == JFileChooser.CANCEL_OPTION){
            return;
        }
        
        String title = filechooser.getSelectedFile().getName();
        
        
        File fileNew = filechooser.getSelectedFile();
        PnlEditor pnlEditor = (PnlEditor) tbpContent.getSelectedComponent();
        
        if( (pnlEditor == null) || (".txt".equals(title))){            // Si se desea guardar un archivo txt y no ha abierto un Editor, retornar
            return;
        }
            
        saveFile(fileNew, pnlEditor);
        
        tbpContent.setTitleAt(index,title);
        JOptionPane.showMessageDialog(null,"File saved successfully");
    }//GEN-LAST:event_mniSaveAsActionPerformed

    private void saveFile(File fileNew, PnlEditor pnlEditor) {
        fileConsequence = new FileConsequence(fileNew);
        String textSave = pnlEditor.getTxtpEditor().getText();
        try {
            fileConsequence.write(fileNew, textSave);
        } catch (IOException ex) {
            Logger.getLogger(FrmEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniTextFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTextFormatActionPerformed
        PnlEditor pnlEditor = (PnlEditor) tbpContent.getSelectedComponent();
        if(pnlEditor == null){
            return;
        }
        
        int option = getFontChooser().showDialog(this);  //Muestra cuadro de dialogo para editar fuentes
        if (option == JFontChooser.CANCEL_OPTION){ //Si presionar cancelar no hace nada
            return;
        }
        
        String text = pnlEditor.getTxtpEditor().getSelectedText(); //Regresa el texto seleccionado
        if (text == null){ //Si no selecciona nada, retorna
            return;
        }
        
        Font font = getFontChooser().getSelectedFont();
        int start = pnlEditor.getTxtpEditor().getSelectionStart(); //Regresa desde donde empieza la seleccion
        StyledDocument style = pnlEditor.getTxtpEditor().getStyledDocument(); //Regresa las fuentes del documento
        pnlEditor.getTxtpEditor().setStyledDocument(getStyledDocuemt(font, style, start, text.length()));
        // Se le aplica la fuente al         (fuente para añadir, estilo del documento a cambiar, seleccion_inicial, seleccion_final
        // archivo con el que se trabaja
    }//GEN-LAST:event_mniTextFormatActionPerformed

    private JFontChooser getFontChooser() {
        if (fontChooser == null) {
            fontChooser = new JFontChooser();
        }
        return fontChooser;
    } 
    
    private void tglBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBoldActionPerformed
        PnlEditor pnlEditor = (PnlEditor) tbpContent.getSelectedComponent();
        if (pnlEditor == null) {
            return;
        }

        String text = pnlEditor.getTxtpEditor().getSelectedText();
        if (text == null) {
            return;
        }

        int start = pnlEditor.getTxtpEditor().getSelectionStart();
        StyledDocument style = pnlEditor.getTxtpEditor().getStyledDocument();

        Font font = new Font(Font.SERIF, tglBold.isSelected() ? Font.BOLD : Font.PLAIN, 14);
        pnlEditor.getTxtpEditor().setStyledDocument(getStyledDocuemt(font,style, start, text.length()));
    }//GEN-LAST:event_tglBoldActionPerformed

    
    private StyledDocument getStyledDocuemt(Font font, StyledDocument style, int start, int length){
        MutableAttributeSet attributeSet = getMutableAttributeSet(style, start);        
        
        attributeSet.addAttribute(StyleConstants.Bold, font.isBold()); //Agrega el tipo de letra NEGRITA si se selecciona
        attributeSet.addAttribute(StyleConstants.Italic, font.isItalic()); //Agrega el tipo de letra cursiva si se selecciona. Al tener las 2 activadas, se puede combinar ambas
        attributeSet.addAttribute(StyleConstants.Size, font.getSize()); // Se agrega el tamaño de letra definida por el usuario
        attributeSet.addAttribute(StyleConstants.Family, font.getFamily()); // Se agrega la fuente definida por el usuario
        attributeSet.addAttribute(StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);
        
        style.setCharacterAttributes(start, length, attributeSet, true); //Se añaden todos los cambios del documento 
        
        return style; // Regresa el estilo del documento con todo y cambios
    }
    
    private MutableAttributeSet getMutableAttributeSet(StyledDocument style, int start) {
        Element element = style.getCharacterElement(start);
        AttributeSet as = element.getAttributes();
        
        return new SimpleAttributeSet(as.copyAttributes());
    }
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNew;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSaveAs;
    private javax.swing.JMenuItem mniTextFormat;
    private javax.swing.JTabbedPane tbpContent;
    private javax.swing.JToggleButton tglBold;
    // End of variables declaration//GEN-END:variables
}
